#!/bin/bash -x

sudo apt-get update
sudo apt-get install -y \
     ccache \
     clang \
     clang-format \
     cmake \
     gnuplot \
     libboost-dev \
     libc++-dev \
     libc++abi-dev \
     linux-tools-generic \
     lld-4.0 \
     lldb \
     plotutils

