#!/bin/bash -x

# Extract the repository name from git.
REPO_NAME=`git -C /vagrant remote show -n origin | grep "Fetch URL:" | sed "s#^.*/\(.*\).git#\1#"`

# Perform a wholesale copy of /vagrant to ~/$REPO_NAME if it is not already there.
if [ ! -d "$REPO_NAME" ]; then
    # Create a new working directory from the original .git. This allows
    # branches, commits, and tags to work seamlessly without losing data
    # when the vagrant instance is inevitably destroyed.
    /bin/bash /usr/share/doc/git/contrib/workdir/git-new-workdir /vagrant $REPO_NAME
fi
